debug: true
items:
  # Food items
  suspicious_stew: 32
  rabbit_stew: 32
  mushroom_stew: 32
  beetroot_soup: 32

  potion: 8
  splash_potion: 8
  lingering_potion: 8

  "*_boat": 4 # All boats
  "*_chest_boat": 4 # All chest boats
  "*_raft": 4 #  rafts
  "*_chest_raft": 4 # chest rafts

  "*minecart": 4 # All minecarts

  saddle: 16

  #"music_disc_*": 16 # All music discs
  #"*_shulker_box": 64 # All shulker boxes